appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
travis:
  secure:
    BINSTAR_TOKEN: DovAuXGBSngidQj/kudgVzvnzrggddXbMsFmt0B1slbTx+wa1uj80Z3/HDEh5GiNzF3TfEAUYw/1PFtCg5LrGjVapZmDLqAijhbBOBC+UVEjiECbVNj8nFEmQDWRah2Ga4uwThaIcG4IrxXHb6wMroD8wPfmRVQxlFEmn/+4ZaWJf4SRGHa9DHnXqYPPpNHDqt8KwSmzarrzUQQg2h3go5bd5bv06Er/7YrmKrOQIWXm/xe0if+fd4bim3Uo3gkcoP4FgcWkvGNiWjIXfcIVI0ZXDF0Fipdi42Ntm8DQ1oW/tOGt0mGkX212z3WMqBAE8M6+H9EtZ/N70NtcdicjhU6Xofa7IizeurNdx0MGHQ4cqZZ2XYxNSWKiysuIiqtjAMTVCCmyg+5vbDZ5f7Wp7xhWzFroQGqGPcPiaB7CGjEteiHwkPp7wRqhgR4ygGm42v116pqsgInF/BFCiG5DUOkahjm8qjoPFeXoIbI2T0R24+M7D5OqMuY6iBwRkaXkVqLnN5v9LFZvoEDHVnCRxgEvkENi1cnx6u3h+8BDBxCWcVUIBSnSUXtp4D9YxaFTlwf8Q92u4syL7nBZIYhZcJD9C6FWJh0WXeCAS76ChF6qcXglsfE39MuXNBk4s0LWX5pNAjxBJqn8JTXz/Y9fjoGYVLYLFIelSL56dfhWECU=
